/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.sanskar.theater

import com.amazonaws.services.lambda.runtime.Context
import com.amazonaws.services.lambda.runtime.RequestHandler
import com.amazonaws.services.lambda.runtime.events.SQSEvent
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import java.io.IOException

class App : RequestHandler<SQSEvent, Unit> {
    override fun handleRequest(event: SQSEvent?, context: Context?) {
        val client = OkHttpClient()
        event?.let { e ->
            e.records.forEach {
                println("sqs message body = ${it.body}")
                val request = Request.Builder()
                    .url("${REPORT_URL}${it.body}")
                    .build()

                client.newCall(request).execute().use { response ->
                    if (!response.isSuccessful) throw IOException("Unexpected code $response")

                    for ((name, value) in response.headers) {
                        println("$name: $value")
                    }

                    println(response.body!!.string())
                }
            }
        }
    }

    companion object {
        const val REPORT_URL = "http://ec2-13-211-62-233.ap-southeast-2.compute.amazonaws.com:8081/reports/generateReport/"
    }
}
